version: 2.1
jobs:

    lint:
        docker:
        - image: python:3.7.3-stretch
        steps:
        - checkout
        - run:
          name: Make install
          command: |
            # Your code here
            cd docker-nginx/
            make install
        - run:
          name: Lint dockerfile and html
          command: |
            # Your code here
            cd docker-nginx/
            make lint
    build:
        docker:
            - image: circleci/python:3.7.3-stretch
        machine: true
        steps:
        - checkout
        #- run: |
            #echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
         
        #build docker image
        - run: |
            cd docker-nginx
            docker build -t melisa87/udacity:capstone  .

        # deploy the image to the DockerHub
        - run: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push melisa87/udacity:capstone

workflows:
  capstone:
    jobs:
      - lint
      - build:
          requires: [lint]