# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
   lint:
      docker:
         - image: python:3.7.3-stretch
      steps:
         - checkout
         - run:
            name: Make install
            command: |
               cd docker-nginx
               make install
         - run:
            name: Lint dockerfile and html
            command: |
               cd docker-nginx
               make lint
   build:
      machine: true
      steps:
         - checkout
         - run: |
            cd docker-nginx
            docker build -t melisa87/udacity:capstone  .

        # deploy the image to the DockerHub
         - run: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push melisa87/udacity:capstone

   create_network:
      docker:
         - image: amazon/aws-cli
      steps:
         - checkout
         - run:
            name: Ensure network infrastructure exist
            command: |
               cd iaac
               aws cloudformation deploy \
               --template-file network.yml \
               --tags project=${ENVIRONMENT_NAME}-Project6 \
               --stack-name capstoneNetwork-${CIRCLE_WORKFLOW_ID}
              

   create_cluster:
      docker:
         - image: amazon/aws-cli
      steps:
         - checkout
         - run:
            name: Create Amazon EKS Cluster
            command: |
               cd iaac
               aws cloudformation deploy \
               --template-file kube-cluster.yml \
               --tags project=${ENVIRONMENT_NAME}-Project6 \
               --stack-name capstoneCluster-${CIRCLE_WORKFLOW_ID} \
               --parameter-overrides file://iaac/kube-cluster-params.json \
               --capabilities CAPABILITY_NAMED_IAM
               
              

workflows:
  capstone:
    jobs:
      #- lint
      #- build:
      #    requires: [lint]
      #- create_network
      - create_cluster