version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
         

     # build the application image
     - run: ls
     - run: cd docker
     - run: ls
     - run: |
        cd docker
        docker build -t melisa/udacity:capstone  .

     # deploy the image
     - run: docker push melisa/udacity:capstone