Description: >
  Melisa Bekan / p6-Capstone Project
  Creates EC2 instances
  
Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: p6-capstone-project
    Type: String
  SSHKeyName:
    Description: SSH key for management access
    Default: udacity
    Type: String
  ImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-0767046d1677be5a0
    Type: String

Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-ec2-SecG
      GroupDescription: Allow port 22 for management
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ec2-instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref ImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2-instance1
        - Key: Project6
          Value: !Ref EnvironmentName

  ec2-instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref ImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2-instance2
        - Key: Project6
          Value: !Ref EnvironmentName